import { Implement } from '@/types';

export const IMPLEMENTS: Implement[] = [
  {
    id: '1',
    name: 'Harrow',
    nameHindi: 'हैरो',
    ratePerUnit: 800,
    unit: 'acre',
    icon: 'grid-3x3',
  },
  {
    id: '2',
    name: 'Cultivator',
    nameHindi: 'कल्टीवेटर',
    ratePerUnit: 800,
    unit: 'acre',
    icon: 'rows-3',
  },
  {
    id: '3',
    name: 'Rotavator',
    nameHindi: 'रोटावेटर',
    ratePerUnit: 2000,
    unit: 'acre',
    icon: 'rotate-cw',
  },
  {
    id: '4',
    name: 'Plough',
    nameHindi: 'हल',
    ratePerUnit: 1600,
    unit: 'acre',
    icon: 'move-diagonal',
  },
  {
    id: '5',
    name: 'MB Plough',
    nameHindi: 'टोटाहल',
    ratePerUnit:3000,
    unit: 'acre',
    icon: 'separator-horizontal',
  },
  {
    id: '6',
    name: 'Seeder',
    nameHindi: 'बीज बोने की मशीन',
    ratePerUnit: 800,
    unit: 'acre',
    icon: 'sprout',
  },
  {
    id: '7',
    name: 'Fertilizer Spreader',
    nameHindi: 'खाद छिड़काव',
    ratePerUnit: 500,
    unit: 'acre',
    icon: 'cloud',
  },
  {
    id: '8',
    name: 'Thresher',
    nameHindi: 'मक्का थ्रेशर',
    ratePerUnit: 2500,
    unit: 'hour',
    icon: 'wheat',
  },
  {
    id: '9',
    name: 'Laser Leveler',
    nameHindi: 'लेजर लेवलर',
    ratePerUnit: 1000,
    unit: 'per hour',
    icon: 'scan-line',
  },
  {
    id: '10',
    name: 'Disc Plough',
    nameHindi: 'डिस्क हल',
    ratePerUnit: 1600,
    unit: 'acre',
    icon: 'circle',
  },
  {
    id: '11',
    name: 'Ridger',
    nameHindi: 'रिजर',
    ratePerUnit: 550,
    unit: 'acre',
    icon: 'mountain',
  },
  {
    id: '12',
    name: 'Sprayer',
    nameHindi: 'स्प्रेयर',
    ratePerUnit: 500,
    unit: 'acre',
    icon: 'droplets',
  },
];

export const LAND_UNITS = [
  { value: 'acre', label: 'Acre', labelHindi: 'एकड़' },
  { value: 'bigha', label: 'Bigha', labelHindi: 'बीघा' },
  { value: 'hectare', label: 'Hectare', labelHindi: 'हेक्टेयर' },
];
